maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 75)
basic.pause(2500)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 75)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 75)
basic.pause(400)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 75)
basic.pause(2500)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 75)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 75)
basic.pause(400)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 75)
basic.pause(2500)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 75)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 75)
basic.pause(400)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 75)
basic.pause(2500)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 75)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 75)
basic.pause(400)
basic.forever(function () {
	
})
